### ISSUE TITLE
Does not work with Composer Autoload

### ISSUE THREAD

**Issue by Patabugen** [OpenCageData/php-opencage-geocode#1]
It's great that this is on Packagist, but it's hard to use because Composer doesn't pick up the classes for autoload

**Comment by mtmail** [comment]
Thanks. I looks like we don't use namespaces as blocks and not according to http://www.php-fig.org/psr/psr-1/ standard. I will change that.

**Comment by mtmail** [comment]
Version 2.0 is published on https://packagist.org/packages/opencage/geocode, enjoy. Let us know if you have any issue or suggestions.
